#!/bin/bash
#
#       /etc/rc.d/init.d/acpid
#
# tmpshm
#
# chkconfig: 345 26 74
# description: tmpshm
# processname: tmpshm

### BEGIN INIT INFO
# Provides: tmpshm
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop tmpshm
# Description: tmpshm
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
SHMPATH=<%= @dir_www %>/tmp
SHMUSER=<%= @user_www %>

start() {
        # Check if it is already running
        if [ ! -f /var/lock/subsys/tmpshm ]; then
            echo -n $"Creating tmpshm disk: "
            mkdir -p $SHMPATH
            mount -t tmpfs -o size=1g,rw,nodev,noexec,nosuid,mode=755 tmpfs $SHMPATH
            chmod 700 $SHMPATH
            chown $SHMUSER $SHMPATH
            mkdir -p $SHMPATH/php_sessions $SHMPATH/php_uploads
            chmod 700 $SHMPATH/php_sessions $SHMPATH/php_uploads
	    chown $SHMUSER $SHMPATH/php_sessions $SHMPATH/php_uploads
            daemon true

            RETVAL=0
            [ $RETVAL -eq 0 ] && touch /var/lock/subsys/tmpshm
            echo
        fi
        return $RETVAL
}

stop() {
    umount $SHMPATH &>/dev/null
    rm /var/lock/subsys/tmpshm
}


restart() {
        stop
        start
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        restart
        ;;
status)
        status tmpshm
        RETVAL=$?
        ;;
*)
        echo $"Usage: $0 {start|stop|restart}"
        RETVAL=2
esac

exit $RETVAL
